// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p/pb/header_request.proto

package p2p_pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_INVALID   StatusCode = 0
	StatusCode_OK        StatusCode = 1
	StatusCode_NOT_FOUND StatusCode = 2
)

var StatusCode_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "NOT_FOUND",
}

var StatusCode_value = map[string]int32{
	"INVALID":   0,
	"OK":        1,
	"NOT_FOUND": 2,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9aef1a6974686dcd, []int{0}
}

type HeaderRequest struct {
	// Types that are valid to be assigned to Data:
	//
	//	*HeaderRequest_Origin
	//	*HeaderRequest_Hash
	Data   isHeaderRequest_Data `protobuf_oneof:"data"`
	Amount uint64               `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *HeaderRequest) Reset()         { *m = HeaderRequest{} }
func (m *HeaderRequest) String() string { return proto.CompactTextString(m) }
func (*HeaderRequest) ProtoMessage()    {}
func (*HeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aef1a6974686dcd, []int{0}
}
func (m *HeaderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeaderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderRequest.Merge(m, src)
}
func (m *HeaderRequest) XXX_Size() int {
	return m.Size()
}
func (m *HeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderRequest proto.InternalMessageInfo

type isHeaderRequest_Data interface {
	isHeaderRequest_Data()
	MarshalTo([]byte) (int, error)
	Size() int
}

type HeaderRequest_Origin struct {
	Origin uint64 `protobuf:"varint,1,opt,name=origin,proto3,oneof" json:"origin,omitempty"`
}
type HeaderRequest_Hash struct {
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
}

func (*HeaderRequest_Origin) isHeaderRequest_Data() {}
func (*HeaderRequest_Hash) isHeaderRequest_Data()   {}

func (m *HeaderRequest) GetData() isHeaderRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *HeaderRequest) GetOrigin() uint64 {
	if x, ok := m.GetData().(*HeaderRequest_Origin); ok {
		return x.Origin
	}
	return 0
}

func (m *HeaderRequest) GetHash() []byte {
	if x, ok := m.GetData().(*HeaderRequest_Hash); ok {
		return x.Hash
	}
	return nil
}

func (m *HeaderRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HeaderRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HeaderRequest_Origin)(nil),
		(*HeaderRequest_Hash)(nil),
	}
}

type HeaderResponse struct {
	Body       []byte     `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	StatusCode StatusCode `protobuf:"varint,2,opt,name=statusCode,proto3,enum=p2p.pb.StatusCode" json:"statusCode,omitempty"`
}

func (m *HeaderResponse) Reset()         { *m = HeaderResponse{} }
func (m *HeaderResponse) String() string { return proto.CompactTextString(m) }
func (*HeaderResponse) ProtoMessage()    {}
func (*HeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aef1a6974686dcd, []int{1}
}
func (m *HeaderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeaderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderResponse.Merge(m, src)
}
func (m *HeaderResponse) XXX_Size() int {
	return m.Size()
}
func (m *HeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderResponse proto.InternalMessageInfo

func (m *HeaderResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HeaderResponse) GetStatusCode() StatusCode {
	if m != nil {
		return m.StatusCode
	}
	return StatusCode_INVALID
}

func init() {
	proto.RegisterEnum("p2p.pb.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*HeaderRequest)(nil), "p2p.pb.HeaderRequest")
	proto.RegisterType((*HeaderResponse)(nil), "p2p.pb.HeaderResponse")
}

func init() { proto.RegisterFile("p2p/pb/header_request.proto", fileDescriptor_9aef1a6974686dcd) }

var fileDescriptor_9aef1a6974686dcd = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x77, 0x6b, 0x58, 0x71, 0x6c, 0x4b, 0x19, 0x44, 0x02, 0xc2, 0x52, 0x7a, 0x2a, 0x1e,
	0x52, 0x89, 0x4f, 0x60, 0x2d, 0xd2, 0xa2, 0x24, 0xb0, 0x7e, 0xe0, 0x2d, 0x6c, 0xc8, 0x62, 0x7a,
	0x30, 0xbb, 0x66, 0x37, 0x07, 0xdf, 0xc2, 0xc7, 0xf2, 0xd8, 0xa3, 0x47, 0x49, 0x5e, 0x44, 0xdc,
	0xd6, 0x8f, 0xdb, 0xfc, 0xf8, 0xfd, 0x99, 0xff, 0x30, 0x70, 0x62, 0x62, 0x33, 0x33, 0xf9, 0xac,
	0x54, 0xb2, 0x50, 0x75, 0x56, 0xab, 0x97, 0x46, 0x59, 0x17, 0x99, 0x5a, 0x3b, 0x8d, 0xcc, 0xc4,
	0x26, 0x32, 0xf9, 0x24, 0x83, 0xc1, 0xd2, 0x7b, 0xb1, 0xd5, 0x18, 0x02, 0xd3, 0xf5, 0xfa, 0x69,
	0x5d, 0x85, 0x74, 0x4c, 0xa7, 0xc1, 0x92, 0x88, 0x1d, 0xe3, 0x11, 0x04, 0xa5, 0xb4, 0x65, 0xd8,
	0x1b, 0xd3, 0x69, 0x7f, 0x49, 0x84, 0x27, 0x3c, 0x06, 0x26, 0x9f, 0x75, 0x53, 0xb9, 0x70, 0xef,
	0x3b, 0x2f, 0x76, 0x34, 0x67, 0x10, 0x14, 0xd2, 0xc9, 0xc9, 0x23, 0x0c, 0x7f, 0x0a, 0xac, 0xd1,
	0x95, 0x55, 0x88, 0x10, 0xe4, 0xba, 0x78, 0xf5, 0xfb, 0xfb, 0xc2, 0xcf, 0x18, 0x03, 0x58, 0x27,
	0x5d, 0x63, 0x2f, 0x75, 0xa1, 0x7c, 0xc3, 0x30, 0xc6, 0x68, 0x7b, 0x63, 0x74, 0xfb, 0x6b, 0xc4,
	0xbf, 0xd4, 0xe9, 0x19, 0xc0, 0x9f, 0xc1, 0x43, 0xd8, 0x5f, 0x25, 0x0f, 0x17, 0x37, 0xab, 0xc5,
	0x88, 0x20, 0x83, 0x5e, 0x7a, 0x3d, 0xa2, 0x38, 0x80, 0x83, 0x24, 0xbd, 0xcb, 0xae, 0xd2, 0xfb,
	0x64, 0x31, 0xea, 0xcd, 0xc3, 0xf7, 0x96, 0xd3, 0x4d, 0xcb, 0xe9, 0x67, 0xcb, 0xe9, 0x5b, 0xc7,
	0xc9, 0xa6, 0xe3, 0xe4, 0xa3, 0xe3, 0x24, 0x67, 0xfe, 0x2b, 0xe7, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x96, 0xd8, 0x63, 0xe8, 0x34, 0x01, 0x00, 0x00,
}

func (m *HeaderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintHeaderRequest(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if m.Data != nil {
		{
			size := m.Data.Size()
			i -= size
			if _, err := m.Data.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *HeaderRequest_Origin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeaderRequest_Origin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintHeaderRequest(dAtA, i, uint64(m.Origin))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}
func (m *HeaderRequest_Hash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeaderRequest_Hash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Hash != nil {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintHeaderRequest(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *HeaderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StatusCode != 0 {
		i = encodeVarintHeaderRequest(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Body) > 0 {
		i -= len(m.Body)
		copy(dAtA[i:], m.Body)
		i = encodeVarintHeaderRequest(dAtA, i, uint64(len(m.Body)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHeaderRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovHeaderRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HeaderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Data != nil {
		n += m.Data.Size()
	}
	if m.Amount != 0 {
		n += 1 + sovHeaderRequest(uint64(m.Amount))
	}
	return n
}

func (m *HeaderRequest_Origin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovHeaderRequest(uint64(m.Origin))
	return n
}
func (m *HeaderRequest_Hash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Hash != nil {
		l = len(m.Hash)
		n += 1 + l + sovHeaderRequest(uint64(l))
	}
	return n
}
func (m *HeaderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Body)
	if l > 0 {
		n += 1 + l + sovHeaderRequest(uint64(l))
	}
	if m.StatusCode != 0 {
		n += 1 + sovHeaderRequest(uint64(m.StatusCode))
	}
	return n
}

func sovHeaderRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHeaderRequest(x uint64) (n int) {
	return sovHeaderRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HeaderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHeaderRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeaderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeaderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Data = &HeaderRequest_Origin{v}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.Data = &HeaderRequest_Hash{v}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHeaderRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeaderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHeaderRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeaderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeaderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = append(m.Body[:0], dAtA[iNdEx:postIndex]...)
			if m.Body == nil {
				m.Body = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= StatusCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHeaderRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHeaderRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHeaderRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHeaderRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHeaderRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHeaderRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHeaderRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHeaderRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHeaderRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHeaderRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHeaderRequest = fmt.Errorf("proto: unexpected end of group")
)
